<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Admin Page</name>
   <tag></tag>
   <elementGuidId>62e4723d-5bf5-4232-951a-4cfb08a2286b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.underline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/footer/div/div/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f6d7a579-605a-49f1-8eec-e504afb147bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline</value>
      <webElementGuid>6bdf2661-e628-4601-958e-e570dc084255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Admin Page</value>
      <webElementGuid>32d17c93-e559-4586-923e-41be96c202ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/footer[@class=&quot;bg-[#301C8A] text-white&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;py-12 flex flex-col xl:flex-row justify-between flex-wrap gap-16&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/a[1]/span[@class=&quot;underline&quot;]</value>
      <webElementGuid>67b5ecdf-847a-42b3-8be5-3a4e25accfc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/footer/div/div/div/a/span</value>
      <webElementGuid>f849529f-5080-4d8d-8e89-18dd65417c3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jonathan Rea'])[1]/following::span[1]</value>
      <webElementGuid>e5fe0dc1-db60-4666-949c-838a39ca59b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alex Espargaro'])[1]/following::span[1]</value>
      <webElementGuid>f2cd7668-2c4b-4a4d-ba4a-15fda2e8140f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/preceding::span[1]</value>
      <webElementGuid>d9f79405-a01a-40c7-ba58-635f2ac0eb0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About us'])[1]/preceding::span[1]</value>
      <webElementGuid>103ed500-917a-46cf-895e-2b7be7fc32c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admin Page']/parent::*</value>
      <webElementGuid>defd55b3-e655-4802-bb28-8fd3a1d5e202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>0dc0395b-2e5f-45fe-9a45-50bbadddcc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Admin Page' or . = ' Admin Page')]</value>
      <webElementGuid>cc04fe31-1710-412e-917b-09abd4b0af48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
